### ISSUE TITLE
Quotes not working

### ISSUE THREAD

**Issue by ianchanning** [jakke-korpelainen/newtab#9]
I'm trying to figure out why the quotes don't seem to be appearing on my localhost version.

Setup: Windows 7 + IIS - IIS could well be the problem.

I've forked and cloned the repository locally, so that its now running at http://localhost/newtab/

I've modified the temperature to be a local Town and that is working as is the background image and the time / date. Just not the quotes.

Firebug isn't showing any errors but Chrome (which also can't display the quote) is showing a few:

```
GET http://localhost/newtab/js/lib/angular-route.min.js.map 404 (Not Found) angular-route.min.js.map:1 
GET http://localhost/newtab/js/lib/angular.min.js.map 404 (Not Found) angular.min.js.map:1 
GET http://localhost/newtab/js/lib/angularAMD.min.map 404 (Not Found) angularAMD.min.map:1 
```

**Comment by jakke-korpelainen** [comment]
Hard to say what seems to be the problem, though your guess is quite good that IIS could have something to do with this.The missing map-files shouldn't be an issue because the other functions work. Could be something related to cross action policy. I'll try to resolve this when I've got time, currently I'm working on user based customizations from json rather than code

**Comment by ianchanning** [comment]
Yeah - IIS wasn't recognising the json MIME type. Fixed it using this blog post: http://www.uipress.com/add-json-handler-support-in-iis-7/
